apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-db
spec:
  replicas: 1
  selector: { matchLabels: { app: customer-db } }
  template:
    metadata: { labels: { app: customer-db } }
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports: [{ containerPort: 5432 }]
          env:
            - name: POSTGRES_DB
              valueFrom: { configMapKeyRef: { name: app-config, key: CUSTOMER_DB } }
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: pg-credentials, key: POSTGRES_USER } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: pg-credentials, key: POSTGRES_PASSWORD } }
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: customer-db
spec:
  selector: { app: customer-db }
  ports:
    - port: 5432
      targetPort: 5432
