apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
spec:
  replicas: 1
  selector: { matchLabels: { app: customer-service } }
  template:
    metadata: { labels: { app: customer-service } }
    spec:
      containers:
        - name: customer
          image: nginx:alpine   # will be replaced by CD
          ports: [{ containerPort: 8000 }]
          env:
            - name: POSTGRES_HOST
              value: customer-db
            - name: POSTGRES_PORT
              valueFrom: { configMapKeyRef: { name: app-config, key: POSTGRES_PORT } }
            - name: POSTGRES_DB
              valueFrom: { configMapKeyRef: { name: app-config, key: CUSTOMER_DB } }
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: pg-credentials, key: POSTGRES_USER } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: pg-credentials, key: POSTGRES_PASSWORD } }
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector: { app: customer-service }
  ports:
    - port: 8000
      targetPort: 8000
