apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector: { matchLabels: { app: order-service } }
  template:
    metadata: { labels: { app: order-service } }
    spec:
      containers:
        - name: order
          image: nginx:alpine   # will be replaced by CD
          ports: [{ containerPort: 8000 }]
          env:
            - name: POSTGRES_HOST
              value: order-db
            - name: POSTGRES_PORT
              valueFrom: { configMapKeyRef: { name: app-config, key: POSTGRES_PORT } }
            - name: POSTGRES_DB
              valueFrom: { configMapKeyRef: { name: app-config, key: ORDER_DB } }
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: pg-credentials, key: POSTGRES_USER } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: pg-credentials, key: POSTGRES_PASSWORD } }
            - name: CUSTOMER_SERVICE_URL
              value: http://customer-service:8000
            - name: PRODUCT_SERVICE_URL
              value: http://product-service:8000
            - name: RABBITMQ_HOST
              valueFrom: { configMapKeyRef: { name: app-config, key: RABBITMQ_HOST } }
            - name: RABBITMQ_PORT
              valueFrom: { configMapKeyRef: { name: app-config, key: RABBITMQ_PORT } }
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector: { app: order-service }
  ports:
    - port: 8000
      targetPort: 8000
