apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels: { app: order-service }
  template:
    metadata:
      labels: { app: order-service }
    spec:
      imagePullSecrets:
        - name: acr-cred
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command: ['sh','-c','until nc -z order-db 5432; do echo "waiting for order-db"; sleep 2; done']
      containers:
        - name: order
          image: kiranacr722.azurecr.io/sit722/order_service:testing-latest
          ports: [{ containerPort: 8000 }]
          readinessProbe:
            httpGet: { path: /, port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 12
          env:
            - name: POSTGRES_HOST
              value: order-db
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: orders
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: ecomm-secrets, key: POSTGRES_USER } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: ecomm-secrets, key: POSTGRES_PASSWORD } }
