apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector: { matchLabels: { app: product-service } }
  template:
    metadata: { labels: { app: product-service } }
    spec:
      containers:
        - name: product     # CD step targets this container name
          image: nginx:alpine   # will be replaced by CD
          ports: [{ containerPort: 8000 }]
          env:
            - name: POSTGRES_HOST
              value: product-db
            - name: POSTGRES_PORT
              valueFrom: { configMapKeyRef: { name: app-config, key: POSTGRES_PORT } }
            - name: POSTGRES_DB
              valueFrom: { configMapKeyRef: { name: app-config, key: PRODUCT_DB } }
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: pg-credentials, key: POSTGRES_USER } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: pg-credentials, key: POSTGRES_PASSWORD } }
            - name: RABBITMQ_HOST
              valueFrom: { configMapKeyRef: { name: app-config, key: RABBITMQ_HOST } }
            - name: RABBITMQ_PORT
              valueFrom: { configMapKeyRef: { name: app-config, key: RABBITMQ_PORT } }
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector: { app: product-service }
  ports:
    - port: 8000
      targetPort: 8000
