apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      imagePullSecrets:
        - name: acr-cred
      containers:
        - name: product
          image: kiranacr722.azurecr.io/sit722/product_service:testing-latest
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: product-db
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: products
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets
                  key: POSTGRES_PASSWORD
